USE QLSINHVIEN
GO

--Bài 1
--1.
CREATE VIEW B1 AS
SELECT CONCAT(HoSV, ' ', TenSV) AS HoTen, MaKH, NoiSinh, HocBong 
FROM SinhVien
WHERE HocBong > 100000 AND NoiSinh = N'Tp.HCM'
GO

--2.
CREATE VIEW B2 AS
SELECT MaSV, MaKH, IIF(Phai=0, N'Nam', N'Nữ') AS Phai
FROM SinhVien
WHERE MaKH='AV' OR MaKH='TR'
GO

--3.
CREATE VIEW B3 AS
SELECT MaSV, NgaySinh, NoiSinh, HocBong 
FROM SinhVien 
WHERE NgaySinh BETWEEN '1986-01-01' AND '1992-06-05'
GO

--4.
CREATE VIEW B4 AS
SELECT MaSV, NgaySinh, IIF(Phai=0, N'Nam', N'Nữ') AS Phai, MaKH
FROM SinhVien
WHERE HocBong BETWEEN 200000 AND 800000
GO

--5.
CREATE VIEW B5 AS
SELECT MaMH, TenMH, Sotiet
FROM MonHoc
WHERE Sotiet>40 AND Sotiet<60
GO

--6.
CREATE VIEW B6 AS
SELECT MaSV, CONCAT(HoSV, ' ', TenSV) AS HoTen, IIF(Phai=0, N'Nam', N'Nữ') AS Phai
FROM SinhVien
WHERE Phai=0 AND MaKH = 'AV'
GO

--7.
CREATE VIEW B7 AS
SELECT CONCAT(HoSV, ' ', TenSV) AS HoTen, NoiSinh, NgaySinh
FROM SinhVien
WHERE NgaySinh>'1990-01-01' AND NoiSinh=N'Hà Nội'
GO

--8.
CREATE VIEW B8 AS
SELECT *
FROM SinhVien
WHERE Phai=1 AND TenSV LIKE '%N%'
GO

--9.
CREATE VIEW B9 AS
SELECT *
FROM SinhVien
WHERE MaKH='TH' AND NgaySinh>'1986-05-30'
GO

--10.
CREATE VIEW B10 AS
SELECT CONCAT(HoSV, ' ', TenSV) AS HoTen,
IIF(Phai=0, N'Nam', N'Nữ') AS Phai, NgaySinh
FROM SinhVien
GO

--11.
CREATE VIEW B11 AS
SELECT MaSV, YEAR(GETDATE())-YEAR(NgaySinh) AS Tuoi, NoiSinh, MaKH
FROM SinhVien
GO

--12.
CREATE VIEW B12 AS
SELECT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen,
YEAR(GETDATE())-YEAR(SV.NgaySinh) AS Tuoi, KH.TenKH
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
WHERE YEAR(GETDATE())-YEAR(SV.NgaySinh) BETWEEN 20 AND 30
GO

--13.
CREATE VIEW B13 AS
SELECT MaSV, IIF(Phai=0, N'Nam', N'Nữ') AS Phai, MaKH,
IIF(HocBong>500000, N'Học bổng cao', N'Mức trung bình') AS HocBong
FROM SinhVien 
GO

--14.
CREATE VIEW B14 AS
SELECT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen,
IIF(SV.Phai=0, N'Nam', N'Nữ') AS Phai, KH.TenKH
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
WHERE KH.TenKH = N'Anh Văn'
GO

--15.
CREATE VIEW B15 AS
SELECT KH.TenKH, CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, MH.TenMH, MH.SoTiet, KQ.Diem
FROM Ketqua KQ
JOIN MonHoc MH ON MH.MaMH = KQ.MaMH
JOIN SinhVien SV ON SV.MaSV = KQ.MaSV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
WHERE KH.TenKH = N'Tin học'
GO

--16.
CREATE VIEW B16 AS
SELECT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.MaKH, MH.TenMH, KQ.Diem,
IIF(KQ.Diem>8, N'Giỏi', IIF(KQ.Diem>=6 AND KQ.Diem<=8, N'Khá', N'Trung bình')) AS Loai
FROM Ketqua KQ
JOIN SinhVien SV ON SV.MaSV = KQ.MaSV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
JOIN MonHoc MH ON MH.MaMH = KQ.MaMH
GO

--17.
CREATE VIEW B17 AS
SELECT KH.TenKH, MAX(SV.HocBong) AS HocBongMax
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
GROUP BY KH.TenKH
GO

--18.
CREATE VIEW B18 AS
SELECT MH.MaMH, MH.TenMH, MH.SoTiet, COUNT(DISTINCT MaSV) AS SoSV
FROM MonHoc MH
JOIN Ketqua KQ ON KQ.MaMH = MH.MaMH
GROUP BY MH.MaMH, MH.TenMH, MH.SoTiet
GO

--19.
CREATE VIEW B19 AS
SELECT TOP(1) WITH TIES MH.TenMH, MH.Sotiet, SV.TenSV, KQ.Diem FROM Ketqua KQ
JOIN SinhVien SV ON SV.MaSV = KQ.MaSV
JOIN MonHoc MH ON MH.MaMH = KQ.MaMH
ORDER BY KQ.Diem DESC
GO

--20.
CREATE VIEW B20 AS
SELECT TOP(1) WITH TIES KH.MaKH, KH.TenKH, COUNT(SV.MaSV) AS SvMax
FROM Khoa KH
JOIN SinhVien SV ON SV.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.TenKH
ORDER BY COUNT(SV.MaSV) DESC
GO

--21.
CREATE VIEW B21 AS
SELECT TOP(1) WITH TIES KH.TenKH, CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, SV.HocBong
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
ORDER BY SV.HocBong DESC
GO

--22.
CREATE VIEW B22 AS
SELECT TOP(1) WITH TIES SV.MaSV, CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.TenKH, SV.HocBong
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
WHERE TenKH = N'tin học'
ORDER BY SV.HocBong DESC
GO

--23.
CREATE VIEW B23 AS
SELECT TOP(1) WITH TIES CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, MH.TenMH, KQ.Diem
FROM Ketqua KQ
JOIN MonHoc MH ON MH.MaMH = KQ.MaMH
JOIN SinhVien SV ON SV.MaSV = KQ.MaSV
WHERE MH.TenMH = N'cơ sở dữ liệu'
ORDER BY KQ.Diem DESC
GO

--24.
CREATE VIEW B24 AS
SELECT TOP(1) WITH TIES CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.TenKH, MH.TenMH, KQ.Diem
FROM SinhVien SV
JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
JOIN MonHoc MH ON  MH.MaMH = KQ.MaMH
WHERE TenMH = N'đồ họa ứng dụng'
ORDER BY KQ.Diem ASC
GO

--25.
CREATE VIEW B25 AS
SELECT TOP(1) WITH TIES KH.MaKH, KH.TenKH 
FROM Khoa KH
JOIN SinhVien SV ON SV.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.TenKH
ORDER BY SUM(IIF(SV.Phai=1, 1, 0)) DESC
GO

--26.
CREATE VIEW B26 AS
SELECT KH.MaKH, KH.TenKH, COUNT(SV.MaSV) AS TongSV,
SUM(IIF(SV.Phai=1, 1, 0)) AS TongNu
FROM Khoa KH
JOIN SinhVien SV ON SV.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.TenKH
GO

--27.
CREATE VIEW B27 AS
SELECT DISTINCT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.TenKH,
IIF(Diem>=4, N'Đậu', N'Trượt') AS KetQua
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
GO

--28.
CREATE VIEW B28 AS
SELECT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.TenKH,
IIF(SV.Phai=0, N'Nam', N'Nữ') AS Phai
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
WHERE SV.MaSV NOT IN (SELECT MaMH FROM Ketqua
					WHERE Diem < 4)
GO

--29.
CREATE VIEW B29 AS
SELECT MaMH, TenMH
FROM MonHoc
WHERE MaMH NOT IN (SELECT MaMH FROM Ketqua
					WHERE Diem < 4)
GO

--30.
CREATE VIEW B30 AS
SELECT MaKH, TenKH 
FROM Khoa
WHERE MaKH NOT IN (SELECT MaKH FROM SinhVien SV
					JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
					WHERE KQ.Diem < 5)
GO

--31.
CREATE VIEW B31 AS
SELECT MH.MaMH, MH.TenMH,
SUM(IIF(KQ.Diem<5, 1, 0)) AS Truot,
SUM(IIF(KQ.Diem>5, 1, 0)) AS Dau
FROM MonHoc MH
JOIN Ketqua KQ ON KQ.MaMH = MH.MaMH
GROUP BY MH.MaMH, MH.TenMH
GO

--32.
CREATE VIEW B32 AS
SELECT MaMH, TenMH FROM MonHoc
WHERE MaMH NOT IN (SELECT MaMH FROM Ketqua
					WHERE Diem < 5)
GO
 
--33.
CREATE VIEW B33 AS
SELECT MaSV, CONCAT(HoSV, ' ', TenSV) AS HoTen, MaKH
FROM SinhVien
WHERE MaSV NOT IN (SELECT MaSV FROM Ketqua
					WHERE Diem < 5)
GO

--34.
CREATE VIEW B34 AS
SELECT SV.MaSV, SV.HoSV, SV.TenSV, SV.MaKH
FROM SinhVien SV
JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
WHERE KQ.Diem < 5
GROUP BY SV.MaSV, SV.HoSV, SV.TenSV, SV.MaKH
HAVING COUNT(KQ.MaMH) > 2
GO

--35.
CREATE VIEW B35 AS
SELECT KH.MaKH, KH.TenKH, COUNT(SV.MaSV) AS TongSV
FROM Khoa KH
JOIN SinhVien SV ON SV.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.TenKH
HAVING COUNT(SV.MaSV) > 10
GO

--36.
CREATE VIEW B36 AS
SELECT SV.MaSV, CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, COUNT(KQ.MaMH) AS SoMon
FROM SinhVien SV
JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
GROUP BY SV.MaSV, CONCAT(SV.HoSV, ' ', SV.TenSV)
HAVING COUNT(KQ.MaMH) > 4
GO

--37.
CREATE VIEW B37 AS
SELECT KH.MaKH, KH.TenKH, COUNT(SV.MaSV) AS TongNam
FROM Khoa KH
JOIN SinhVien SV ON SV.MaKH = KH.MaKH
WHERE SV.Phai = 0
GROUP BY KH.MaKH, KH.TenKH
HAVING COUNT(SV.MaSV) >= 5
GO

--38.
CREATE VIEW B38 AS
SELECT CONCAT(SV.HoSV, ' ', SV.TenSV) AS HoTen, KH.TenKH,
IIF(SV.Phai=0, N'Nam', N'Nữ') AS Phai, AVG(KQ.Diem) AS Dtb
FROM SinhVien SV
JOIN Khoa KH ON KH.MaKH = SV.MaKH
JOIN Ketqua KQ ON KQ.MaSV = SV.MaSV
GROUP BY CONCAT(SV.HoSV, ' ', SV.TenSV), KH.TenKH, SV.Phai
HAVING AVG(KQ.Diem) > 4
GO

--39.
CREATE VIEW B39 AS
SELECT MH.MaMH, MH.TenMH, AVG(KQ.Diem) AS Dtb
FROM MonHoc MH
JOIN Ketqua KQ ON KQ.MaMH = MH.MaMH
GROUP BY MH.MaMH, MH.TenMH
HAVING AVG(KQ.Diem) > 6
GO
